services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.develop
    ports:
      - 3000:8000
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - zion-network

  db:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: zion
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - zion-network

networks:
  zion-network:
